### ISSUE TITLE
Pre-cleaner issues

### ISSUE THREAD

**Issue by akolonin** [singnet/language-learning#187]
Fix multiple pre-cleaner issues, based on:
http://langlearn.singularitynet.io/data/akolonin_studies/gutenberg_children_cleaned_wordcounts.txt
Specific problems:
1. @alexei-gl : "up.'and" token in parse instead of "up" which was the right word in original corpus sentence. I ran though grammar rules in 4.0.dict file, induced by grammar learner, and found token "up.'and" in one of the grammar rules. Apparently Link Grammar interpret it as token "up" with suffix "'and" which leads to error in parsing when parsed by link-parser testing the grammar because "up.'and" and "up" are located in different gramma rules (clusters). The same goes for "..y" which is interpreted by link-parser as token "." with suffix "y".
2. Many situation when unparsed periods (dots) are hanging past words - for example:
assume.	1
associates.	1

**Comment by glicerico** [comment]
The aforementioned examples are not problems with the pre-cleaner:
1a) "up.'and" is actually a typo in the corpus where a space is missing in the original sentence. The pre-cleaner doesn't split dots and apostrophes inside words.
1b) "..y" (and it's variants with more dots) is actually coming from a bug in our link-parser wrapper, which I remember that @alexei-gl was aware of. The wrapper failed to remove the LG tag for a single dot.

**Comment by glicerico** [comment]
For 2), I see this word count is coming from june 2018. Now that we're using the LG tokenization, these counts should not appear anymore.

**Comment by akolonin** [comment]
We can have any situations in any kinds of corpus for any kinds of languages other than English and pre-cleaner should be configurable and stable enough to handle all that. Using LG-English tokenization can not be thought as a solution for _unsupervised learning_ project even for English, leave alone all other 6,500 languages on Earth.

**Comment by akolonin** [comment]
It is clearly fine to use LG-English tokentization for current iteration as a temporary hack but we will have to go back to the pre-cleaner and/or unsupervised tokenization at some point.

**Comment by glicerico** [comment]
@akolonin , I agree with you that unsupervised pre-cleaning and tokenization would be needed in the long term. However, none of the problems described in this issue should be handled by the pre-cleaner. What actions would be needed to close this issue?

**Comment by akolonin** [comment]
1) "up.'and"  - let's ignore this issue for now

2) "associates." - fix pre-cleaner so it never keeps period in the end of sentence attached to word - the ending period past word should be treated as separate token. 

3) also, it should be possible to configure pre-cleaner to have periods dropped as skip-word (but the latter option should be off by default).

**Comment by glicerico** [comment]
@akolonin ,
1) Agree, pre-cleaner cannot handle all possible scenarios. A possible and complex solution to this is the dynamic tokenizer that Linas has been talking about in Link Grammar.
2) The pre-cleaner was never meant to be a tokenizer. If you look at a pre-cleaned file (e.g. http://langlearn.singularitynet.io/data/cleaned/English/Gutenberg-Children-Books/lower/11-0.txt) you'll see that all sentences that had a final dot are keeping it in place. On the other hand, the tokenizer is in charge of splitting that final dot; if you look at the tokenized files (e.g. http://langlearn.singularitynet.io/data/cleaned/English/Gutenberg-Children-Books/lower_tokenized_LG5.5.1/11-0.txt.ull) you see the final dot is separated. The file that you refer in your original point 2) in this issue is a cleaned file, not a tokenized file, and that's why your word counts includes things like "associates."
3) That option already exists. The pre-cleaner can eliminate single characters if asked to: https://github.com/singnet/language-learning/blob/92ca520a97d1f0c48bf644eb24b062307ae55e96/src/pre_cleaner/pre_cleaner.py#L23
P.S.) I have that in mind, so that's why we decided that we DON'T want to use the LG tokenized in our pipeline, and I removed its use from our pipeline, deferring the tokenizing step to some other algorithm (in practice we're now using LG-English, but this should be something unsupervised in the future, as you say).

**Comment by akolonin** [comment]
@glicerico  re: 2) I see, but all these tokens with literals ending with period make no sense - can we just have periods separated from literals like we do for any other punctuation - commas, question and exclamation marks? 
Looks like linkparser should be happy about that:
```
linkparser> he got behind alice as he spoke.
Found 4 linkages (4 had no P.P. violations)
	Linkage 1, cost vector = (UNUSED=0 DIS= 0.04 LEN=10)

    +--------------------------Xp--------------------------+
    +---->WV--->+--------Pa--------+       +----CV-->+     |
    +->Wd--+-Ss-+---MVp--+         +--MVs--+-Cs+--Ss-+     |
    |      |    |        |         |       |   |     |     |
LEFT-WALL he got.v-d behind.p alice[?].a as.e he spoke.v-d .

Press RETURN for the next linkage.
linkparser> he got behind alice as he spoke .
Found 4 linkages (4 had no P.P. violations)
	Linkage 1, cost vector = (UNUSED=0 DIS= 0.04 LEN=10)

    +--------------------------Xp--------------------------+
    +---->WV--->+--------Pa--------+       +----CV-->+     |
    +->Wd--+-Ss-+---MVp--+         +--MVs--+-Cs+--Ss-+     |
    |      |    |        |         |       |   |     |     |
LEFT-WALL he got.v-d behind.p alice[?].a as.e he spoke.v-d .

Press RETURN for the next linkage.
```

**Comment by akolonin** [comment]
It does not make sense to create two words from one just because the word has turned unhappy to stay in the very end of the sentence:
akolonin@Ubuntu-1604-xenial-64-minimal:~/public/akolonin_studies$ grep ^it gutenberg_children_cleaned_wordcounts.txt
it	30863
it.	4433
...
italy	5
italy.	5

**Comment by akolonin** [comment]
@glicerico if you fix that, please place re-generate GC "cleaned" corpus and put it aside for future work

**Comment by glicerico** [comment]
@akolonin , I'll fix this. But just for the record:
> It does not make sense to create two words from one just because the word has turned unhappy to stay in the very end of the sentence:
there is no creation of two words other than in that wordcount file, because once the tokenizer processes the text, the dot gets separated... the "two words" don't make it to the word space vector.

**Comment by akolonin** [comment]
> because once the tokenizer processes the text

**Comment by glicerico** [comment]
> This happens in LG-Parser and OpenCog MI-counter but not in DNN-MI-lker, right?
It also happens in DNN version, because we feed it pre-tokenized text

**Comment by glicerico** [comment]
@akolonin , I worked on pre-cleaner update and unit tests. Default is now to separate dots from end of words, as requested. Changes in PR# https://github.com/singnet/language-learning/pull/230
Also, newly cleaned corpus, including some other fixes done in pre-cleaner, can be found in the ULL server in
/home/asuarez/CORPORA/English/Children/Gutenberg_Children_Books/cleaned_18-06-2019
I will do a couple more minor fixes to pre-cleaner and then show you and @alexei-gl on how to use it.

**Comment by akolonin** [comment]
@glicerico - can you turn the pg26041.txt_headless_split_default to pg26041.txt so we have *.txt files ?

**Comment by glicerico** [comment]
No problem, so we want no description of the pre-processing in the file
names at all, right?

**Comment by akolonin** [comment]
> No problem, so we want no description of the pre-processing in the file
names at all, right?

I am not sure what the "_headless_split_default" says and it makes the files hardly handleable by hands and I guess the following pipeline. What does such extension buy us and why can't we place details in the readme?

Other than that - have looked into maximum sentence length (MSL) of sentences:

$ cat * | awk 'NF' | sort | awk '{print NF}' | sort | uniq -c | sort -k 2,2 -n
    898 1
   2078 2
   3908 3
   5033 4
   6864 5
   9032 6
  10090 7
  10982 8
  11473 9
  11484 10
  11476 11
  10904 12
  10583 13
  10375 14
   9874 15
   9360 16
   9019 17
   8667 18
   8266 19
   7878 20
   7482 21
   6984 22
   6661 23
   6403 24
   6063 25

Based on that, to enable further "curriculum learning" work, can you create one more subfolder level and 
A) place current content (MSL=25) into subfolder called msl25
B) create subfolders msl=5,10,15,20 and fill them with respective content
?

**Comment by glicerico** [comment]
@akolonin the precleaner is now modified to avoid adding suffixes to filenames. Instead, user is responsible to name the directories with sufficient description. Files are in /home/asuarez/CORPORA/English/Children/Gutenberg_Children_Books/cleaned/
The suffixes were initially added to keep track of the pre-processing that was done to the original Project Gutenberg files, like removing header and footers (e.g. the terms of use of Project Gutenberg's books), splitting the file per sentence, as well as parameters used in pre-cleaner.
Now, I added the cleaning date to the folder names, because that's a way of knowing what were the precleaner's default parameters valid at the moment (you see, we have changed those a few times during the project already).

**Comment by akolonin** [comment]
@glicerico @alexei-gl - having the parameters footprint in folder name makes much more sense than having it it every file name. However, the _pipeline idea and style_ is to let the people and pipeline itself to handle folder naming based on parameters, not giving this right to the every individual component.

**Comment by glicerico** [comment]
That makes sense, except that pre-cleaner is not part of the pipeline yet.
Also, I find it hard to imagine pre-cleaner could be completely automated,
since each different corpus may have really different characteristics. I've
had the idea that pre-cleaner should be done manually before feeding to the
pipeline.

**Comment by akolonin** [comment]
The plan is to have part of pipeline and settings to be parameters. We are on the long way :-)

**Comment by glicerico** [comment]
Can we close this issue?
