### ISSUE TITLE
Broken sentences and extra MST parses due to OpenCog sentence-splitter problem

### ISSUE THREAD

**Issue by akolonin** [singnet/language-learning#94]
For Gutenberg Children, MST Parses (207132) are returning 2 extra parses, compared to input corpus and compared to LG parses (207130) - not the end of the world but something that we need to understand (need to provide a workaround and correct parses or wait of OpenCog GitHub issue fixed).

Depends on OpenCog issue: https://github.com/opencog/opencog/issues/3282

~/data/parses/English/Children/Gutenberg_Children_Books/MST_win6_omdist
cat Children-parses-win6-omdist.ull | uniq | sort | uniq -c | head -n 1
207132
cat Children-parses-win6-omdist.ull | uniq | grep -cvP '\S'
207132
~/data/parses/English/Children/Gutenberg_Children_Books/MST_win6_omdist/Children-parses-win6-omdist
cat * | uniq | sort | uniq -c | head -n 1
207132
cat * | uniq | grep -cvP '\S'
207132
~/data/parses/English/Children/Gutenberg_Children_Books/MST_win6_omdist/Children-win6-omdist_sameparses
cat * | uniq | sort | uniq -c | head -n 1
191021
cat * | uniq | grep -cvP '\S'
191021
It looks like ~/data/parses/English/Children/Gutenberg_Children_Books/MST_win6_omdist/Children-parses-win6-omdist have the same number of parses as ~/data/parses/English/Children/Gutenberg_Children_Books/MST_win6_omdist/Children-parses-win6-omdist.ull

Also, it looks like the ~/data/parses/English/Children/Gutenberg_Children_Books/MST_win6_omdist/Children-win6-omdist_sameparses is missing 16111 parses - what is the reason to consider the latter?

Here is what I see in cleaned corpus:
~/data/cleaned/English/Children/cleaned_Gutenberg_Children/capital$ cat * | awk 'NF' | wc -l
207130
Andres, I recall you was removing some files from ~/data/parses/English/Children/Gutenberg_Children_Books/MST_win6_omdist/Children-win6-omdist_sameparses entirely, so it explains the reason.
Now, looking into LG parses:
~/data/parses/English/Children/Gutenberg_Children_Books/LG/capital/parses
cat * | uniq | sort | uniq -c | head -n 1
207130
cat * | uniq | grep -cvP '\S'
207130
I see that MST Parses (207132) are returning 2 extra parses, compared to input corpus and compared to LG parses (207130) - not the end of the world but something that we need to understand.

@glicerico 
Issue was raised about underscore not identified as sentence splitter: https://github.com/opencog/opencog/issues/3282

The pre-cleaning process calls sentence-splitter, which doesn't cut the sentence with underscore. Then pre-cleaner cleans underscore, then when calling sentence-splitter again, it cuts the sentence. Since LG-English doesn't call sentence splitter a second time, then it doesn't cut the sentence.

I just realized pre-cleaner should not escape backslashes and double quotes (as currently done in workaround), because LG-English doesn't recognized the escaped mark (\) and will parse differently

**Comment by akolonin** [comment]
@glicerico - can removal of underscores as white spaces accordingly to pre-cleaner settings (making that as default) let the problem go away? We have this in spec https://docs.google.com/document/d/1xgO6CREtXzYG8k1_8-ixUNUEEnmOTsYX1tWp7gEscc0/edit# :
"6. Symbols splitting tokens (symbol appearing in token splits it): whitespaces (space, \t, \n, \r, long dash, underscore, asterisk)."

**Comment by glicerico** [comment]
@akolonin 
"can removal of underscores as white spaces accordingly to pre-cleaner settings (making that as default) let the problem go away?" ==> No, pre-cleaner works according to that specification already, and this way of handling underscores is actually part of the problem, because pre-cleaner removes the underscore, and when the MST-pipeline uses sentence-splitter again (now without underscore) then the sentence is split into two.

**Comment by akolonin** [comment]
@glicerico , since @pennachin says "issue that should be handled with preprocessing", removal of white-spaces by pre-cleaner should be done before splitting the sentences, will this work?

**Comment by glicerico** [comment]
@akolonin , removing token-splitter characters before sentence-splitting would add complication to the pipeline, since we would need to run a pre-pre-cleaner, then sentence splitter, then pre-cleaner.
What I'm thinking is that I can modify our local copy of the pre-cleaner (which is already modified to not escape double quotes and backslashes) and make it handle underscore breaking a sentence if it comes after a dot (just like other beginning of sentence markers like "¿" or "¡"  are handled).

**Comment by glicerico** [comment]
This sentence-splitter problem was fixed in opencog/opencog#3282
